### ISSUE TITLE
Update the JS-API so that its functionality matches the v5.2 Core APIs

### ISSUE THREAD

**Issue by john-knowles** [Alfresco/alfresco-js-api#196] opened 2017-03-08 14:30 UTC
**Current behaviour:**
JS-API does not currently cover all the APIs available in Alfresco Content Services.

**Expected behaviour:**
The JS-API makes available all the functionality of the Alfresco Content Services APIs.

**New feature request:**

As a developer building an application using the ADF I want to fully utilise the features in the Alfresco Content Services platform.

**Current Content Services JS-APIs:**
- Get Node content
- Get File or Folder Info
- Get Folder Children Info
- Create Folder
- Upload File
- Events Upload File
- Delete File or Folder
- Delete File or Folder Permanent
- Get thumbnail Url
- Get preview Url
- Get content Url
- Custom web scripts call

**Content Services REST API as per version 5.2:**
As per: https://api-explorer.alfresco.com/api-explorer/

**Comment by magemello** [comment] 2017-03-08 18:28
Hi John, is this issue related to the search API? if so is a duplicate of #194 
In case not can you please add more details.

**Comment by john-knowles** [comment] 2017-03-08 21:16
@magemello thanks!  I was about to list all the APIs detailed at https://api-explorer.alfresco.com/api-explorer/ because the main README.md for this project doesn't contain information about all those APIs, for example Favourites, People, and so on.

However this https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-core-rest-api/README.md does have more listed. 

I am not sure what if any gap there is between the v5.2 Core REST APIs and the JS-API; so if there is a gap then this request is to close that gap.

**Comment by magemello** [comment] 2017-03-08 21:53
The known gaps are:
- Missing Versions
- deleted-nodes has to be moved inside the new TrashCan name (but all the end point are already present and working).

**Comment by john-knowles** [comment] 2017-03-08 22:12
Sounds good!  For creating a shared link can the expiry time be applied?
https://api-explorer.alfresco.com/api-explorer/#!/shared-links/createSharedLink

**Comment by magemello** [comment] 2017-03-09 18:43
https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-core-rest-api/docs/SharedlinksApi.md ?

**Closed** 2017-10-24 13:57 UTC
