### ISSUE TITLE
[NodeJs, Ts] misleading type information for type Blob from getNodeContent method

### ISSUE THREAD

**Issue by timlohse1104** [Alfresco/alfresco-js-api#1343] opened 2022-03-03 13:40 UTC
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

When calling getNodeContent method defined in https://github.com/Alfresco/alfresco-js-api/blob/cdeecd6f62481fc025f902d9cdf4d8b5f26638b9/src/api/content-rest-api/api/nodes.api.ts#L829 which should return `Promise<Blob>`  misleads to NodeJs Blob due to missing import of https://github.com/Alfresco/alfresco-js-api/blob/cdeecd6f62481fc025f902d9cdf4d8b5f26638b9/src/alfrescoApiClient.ts#L26. 

**Expected behavior:**

Alfresco types don't clash with internal NodeJs types.

**Node version (for build issues):**  

v16

**Comment by DenysVuika** [comment] 2023-06-16 09:41
duplicate of https://github.com/Alfresco/alfresco-js-api/issues/1139

**Closed by DenysVuika** 2023-06-16 09:41 UTC
